In [2]:
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np

In [5]:
from sklearn.cross_validation import train_test_split

In [7]:
from sklearn.naive_bayes import GaussianNB

In [16]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [3]:
iris = load_iris()

In [4]:
data = iris.data
target = iris.target

In [11]:
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state = 1)

In [9]:
# defining the model
model = GaussianNB()

In [12]:
# fit the data into the model
model.fit(X_train, y_train)

GaussianNB(priors=None)

In [13]:
# test-predicting the remaining splitted data
y_pred = model.predict(X_test)

In [14]:
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [15]:
y_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [21]:
mat = confusion_matrix(y_test, y_pred)
# plt.xlabel('Original Target')
# plt.ylabel('Predicted Target')

In [18]:
mat

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [38]:
print('Enter the sepal length: ')
sepal_length = float(input())

print('Enter the sepal width: ')
sepal_width = float(input())

print('Enter the petal length: ')
petal_length = float(input())

print('Enter the petal width: ')
petal_width = float(input())

Enter the sepal length: 
3
Enter the sepal width: 
7
Enter the petal length: 
8
Enter the petal width: 
2


In [41]:
user = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
# user = user[:, np.newaxis]

In [42]:
user_predict = model.predict(user)

In [43]:
user_predict

array([2])

In [37]:
user

array([[ 7.],
       [ 8.],
       [ 9.],
       [10.]])